-- Create User and Session tables, and add userId relations across entities

-- CreateTable: User
CREATE TABLE IF NOT EXISTS "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "name" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- Unique index on email
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'User_email_key' AND n.nspname = 'public'
    ) THEN
        CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
    END IF;
END$$;

-- CreateTable: Session
CREATE TABLE IF NOT EXISTS "Session" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3),
    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- Unique index on token
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'Session_token_key' AND n.nspname = 'public'
    ) THEN
        CREATE UNIQUE INDEX "Session_token_key" ON "Session"("token");
    END IF;
END$$;

-- Add foreign key Session.userId -> User.id
ALTER TABLE "Session"
    ADD CONSTRAINT IF NOT EXISTS "Session_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Ensure Settings has an auto-increment id and userId relation
-- Drop default on id if exists and convert to identity for auto-increment
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'Settings' AND column_name = 'id'
    ) THEN
        BEGIN
            ALTER TABLE "Settings" ALTER COLUMN "id" DROP DEFAULT;
        EXCEPTION WHEN others THEN
            -- ignore if no default
            NULL;
        END;
        BEGIN
            ALTER TABLE "Settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
        EXCEPTION WHEN others THEN
            -- ignore if already identity
            NULL;
        END;
    END IF;
END$$;

-- Add userId to Settings
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'Settings_userId_key' AND n.nspname = 'public'
    ) THEN
        ALTER TABLE "Settings" ADD CONSTRAINT "Settings_userId_key" UNIQUE ("userId");
    END IF;
END$$;

ALTER TABLE "Settings"
    ADD CONSTRAINT IF NOT EXISTS "Settings_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Add userId to Invoice
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "Invoice"
    ADD CONSTRAINT IF NOT EXISTS "Invoice_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Add userId to Payment
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "Payment"
    ADD CONSTRAINT IF NOT EXISTS "Payment_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Add userId to Customer
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "Customer"
    ADD CONSTRAINT IF NOT EXISTS "Customer_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Add userId to Product
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL;
ALTER TABLE "Product"
    ADD CONSTRAINT IF NOT EXISTS "Product_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;